apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: unianalytics-ingress
  namespace: unianalytics
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - unianalytics.uz
        - "*.unianalytics.uz"
      secretName: unianalytics-tls
  rules:
    - host: unianalytics.uz
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-svc
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-svc
                port:
                  number: 80
